movieproject/movieapp/urls.py
from django.urls import path

from movieapp import views
app_name='movieapp'

urlpatterns = [

    path('',views.index,name='index'),
    path('<int:movie_id>',views.detail,name='detail'),
    path('add/',views.add,name='add'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete'),


]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),

]

if settings.DEBUG :
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models


# Create your models h
class movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='pics')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import movie
class movieforms(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.shortcuts import render, redirect

# Create your views here.
from movieapp.forms import movieforms
from movieapp.models import movie


def index(request):
    mlist = movie.objects.all()
    return render(request, 'index.html', {'mlist': mlist})


def detail(request, movie_id):
    mlist = movie.objects.get(id=movie_id)
    return render(request, 'detail.html', {'mlist': mlist})

def add(request):
    if request.method=='POST':
        name=request.POST['name']
        desc=request.POST['desc']
        year=request.POST['year']
        img=request.FILES['img']
        movies=movie(name=name,desc=desc,year=year,img=img)
        movies.save()
        return redirect('/')
    return render(request,'add.html')


def update(request,id):
    mlist=movie.objects.get(id=id)
    form=movieforms(request.POST or None,request.FILES,instance=mlist)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'update.html',{'form':form,'movie':mlist})

def delete(request,id):
    if request.method=='POST':
        mlist=movie.objects.get(id=id)
        mlist.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter movie name"></br>
    <input type="text" name="desc" placeholder="Enter description"></br>
    <input type="text" name="year" placeholder="Enter movie year"></br>
    <input type="file" name="img"></br>
    <input type="submit">

</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="post">
  {% csrf_token %}
  Do you want to delete this movie
  <input type="submit">
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="'col-md-6">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{mlist.img.url}}" alt="Card image cap" height="450">

            </div>
        </div>
             <div>
                 <h6>{{mlist.desc}}</h6>
                 <h5>year:{{mlist.year}}</h5>
                 <a href="{% url 'movieapp:update' mlist.id %}" class="btn btn-warning">Update</a>
                 <a href="{% url 'movieapp:delete' mlist.id %}" class="btn btn-danger">Delete</a>
             </div>

    </div>
</div>
{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
 <div class="row">
  {% for i in mlist %}
  <div class="col-md-3">
   <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="450">
    <div class="card-body">
     <h5 class="card-title">{{i.name}}</h5>
     <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Go to details</a>
     <a href="{% url 'movieapp:add' %}" class="btn btn-secondary">Add new movie</a>
    </div>
   </div>
  </div>
  {% endfor %}
 </div>
</div>
{% endblock %}

movieproject/templates/update.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>